insert into usuario values(1,'Panadería Mildred','Pirujo de leche y yemas, el Original Pan Dormido, Semitas de Panela e integrales y sin falta la Sheca Sampedrana blanca con Ajonjolí','San Pedro Sac. San Marcos','Fue fundada por su propietario, que cuenta que a las edad de 10 años empezó a sentir atracción por la elaboración del tradicional pan sampedrano: “Shecas”, y en ese afán empezó a ayudar a su tía Antolina Orozco a amasar Semitas y Tortas para Shecas blancas con Ajonjolí (receta que ha mantenido hasta el día de hoy). Fue entonces, a la edad de 14 años, que empezó a aprender otras recetas, así como la elaboración de otros tipos de pan, de corte popular como el Pan Desabrido, el Pan Tostado y Pan Dulce en sus diferentes presentaciones. Al contraer nupcias con su esposa, fue cuando inició el proyecto de su vida, inauguraron su panadería, que lleva el nombre de Mildred, en honor de su hija “primogénita”, en el año 1971. De esa fecha para acá, define su panadería como exitosa, de confianza y el sabor que ha mantenido por año lo identifica con un local de prestigio y sus clientes han sido fieles por su sabor y tradición, que los distingue.','','7760 7671 / 5191 9175','Hermelindo Alfredo Velásquez Ordoñez - Idalia Orozco Orozco (Q.E.P.D.)','',now(),now());






insert into usuario values(2,'Panadería Anita','Bollos, Shecas Sampedranas, Semitas, Jaleas, Roscas y el Tradicional Pan Dormido','San Pedro Sac. San Marcos','Fue doña Ana Godínez quien tuve la brillante idea de fundar la panadería al lado de su señor esposo, don Alfonso Monzón en el año de 1969. Sin embargo, doña Anita ya elaboraba el tradicional Pan Sampedrano desde la edad de los 10 años. Ella quedo huérfana a muy temprana edad, por lo que se vio obligada a trabajar y se dedicó por completo a la elaboración de pan, con lo que ha sacado adelante a tu familia. Este arte fue heredado a su hija Vilma Floriselva Monzón Godínez, quien también empezó desde muy temprana edad, demostrando dotes administrativos, por lo que le dejan a cargo el negocio familiar, ella junto a su esposo don Lui Humberto, han trascendido con este legado al punto de que ahora una tercera generación encabezada por el niño Luis Alfonso Navarro Monzón de tan solo 5 años de edad, ya se involucró por completo al negocio de la familia, garantizando de esta maneran que otras generaciones disfrutarán de este maravilloso manjar sampedrano. Para nosotros es un verdadero gusto trabajar en esto –mencionan-, pues mantenemos vivo el legado de nuestra madre “Doña Anita” y esperamos darnos a conocer aún más ya que actualmente nuestra labor sampedrana lo vendemos en otros municipios del departamento, incluso traspasando fronteras, pues hemos encontrado un nicho de mercado en Tapachula, Chiapas del vecino país México.','','3167 7165','Vilma Floriselva Monzón Godínez Luis Humberto Navarro Ramírez (Esposos)','',now(),now());




insert into usuario values(3,'Venta de Pan de Doña Maru','Pan Dormido, Cazuelejas, Bollos, Biscochos, Sheca, Semita Rellena y Francés de Leche','Interior del Mercado No. 2 San Pedro Sac. San Marcos','sta venta de Pan se encuentra ubicada en el Centro Comercial No. 2, pero la elaboración del pan se realiza en su casa de habitación. Los propietarios cuentan que la elaboración del Pan Sampedrano, ha sido una herencia con muchos años de tradición, pues fue doña Gabriela Godínez hace ya aproximadamente 80 años, quien trajo este noble arte a la familia, siendo ella originaria de Caserío Los Jazmines, del municipio de San Pedro Sac., del Departamento de San Marcos. Luego de su fallecimiento, hace ya muchos años, fue doña Calixta Godínez, quien se hizo cargo de la elaboración del pan ya tradicional de la Venta de Doña Maru y luego de su fallecimiento, queda a cargo del negocio y de la elaboración de esta exquisitez culinaria, doña María Velásquez, quien actualmente ya descansa en paz por lo que los esposos Fuentes Velásquez, quedan a cargo desde hace muchos años del negocio que hasta el momento ha sobrevivido 4 generaciones, inculcándole ellos a sus hijos e hijos políticos el amor por la elaboración del pan tradicional de San Pedro, siendo todos ellos ahora el equipo que conforma el negocio tradicional de Doña Maru. Doña Maru, ha sido el nombre con que los identifican, pues cuenta así le llamaban a una de las propietarias ya fallecida Doña Maru o Doña Maruca, aunque en realidad su nombre era María, se identifican asimismos como propietarios de un negocio próspero que representa la unidad familiar y el legado de sus bisabuelos, quienes tuvieron a bien traer este arte a la familia.','','','Lidia Elizabeth Velásquez Velásquez - Freddy Fuentes (Esposos)','',now(),now());



insert into usuario values(4,'Panadería La Empanadita','Empanadas de Manjar, Semitas Rellenas, Pan de Yemas, Pan Dormido, Cubiletes de Naranja y Cubiletes de Banano, Pirujo de Leche, Pirujo de Yemas y Pan Dulce','San Pedro Sac. San Marcos','Panadería la Empanadita, fue fundada por doña Carmen, como forma de contribuir a la economía familiar, siendo ella ayudada por su hija mayor y de uno de los propietarios don Ernesto Nehemías López López, quienes se dieron a la tarea de ir a vender casa por casa, sus tradicionales empanadas, que en un principio eran elaboradas con una estufa con horno. Doña Carmen junto a sus hijos, quienes de muy temprano y antes de involucrarse en sus actividades tanto del hogar, como en la escuela respectivamente, se levantaban a amasar la materia prima para las empanadas y posteriormente los cubiletes; luego de ver que su producto tenía demanda con los vecinos y conocidos, deciden construir un horno de leña tradicional y doña Carmen junto a su familia, especialmente su hijo, construyen ellos su horno. Empezando con esto la segunda fase y como ellos la describen, la más maravillosa, para el negocio familiar. Teniendo ya el horno, se deciden a cocinar en él diferentes clases de pan, de corte popular, pero sin dejar a un lado el tradicional Pan Shecano. Un evento que marcó un antes y un después de este negocio, fue el terremoto del año 2012, que dejo casi destruido el horno que con mucho esfuerzo, esmero y dedicación habían construido, siendo este un punto de inflexión, donde la decisión era continuar con el negocio o desaparecer del mercado; sin embargo la determinación los hace surgir como el fénix desde la cenizas e inicia una etapa, donde han logrado montar una tienda en un local físico, sin dejar de lado su tradición de llevar puerta por puerta, a cuestas el sabor tradicional de la Panadería la Empanada. Este negocio ha sido rentable, para el sustento familiar, que ahora Ernesto mejor conocido como Canchito o Meshito, desarrolla su labor comercial, haciendo la función de un café ambulante, quien junto a su esposa e hijos, llevan a los negocios del Centro de este municipio en horas de la tarde el sabor de sus deliciosos panes y empanadas, acompañados de una taza de café donde su única finalidad es hacer crecer el negocio para que sea próspero y sus cliente puedan seguir disfrutando el sabor que tanto les gusta.','','52215481','Carmen Consuelo López Chávez','',now(),now());



insert into usuario values(5,'Panificadora Rosita','Pan de Trigo con Relleno Blanco, Pan de Jalea, Tortas, Bollos Volteados, Rellenas Amarillas, Roscas y su especialidad el Pan Dormido ','San Pedro Sac. San Marcos','La historia de Panificadora Rosita, data de mucho tiempo atrás, donde los abuelos de la ahora propietaria don Eligio González y doña Carmen Juárez inician con el Negocio, heredándoselo a sus hija Delfina González (En Paz Descanse) mamá de Doña Rosalinda Rivera González, quien está a cargo de la panificadora. En época donde los fundadores, empezaron a comercializar su pan, las personas que venían de otros municipios y departamentos, venían acompañados de cajones para llevar el pan, para que llegara en perfectas condiciones y ser disfrutado en cada hogar de destino de este producto Sampedrano, muchos años pasaron y acontecimientos hasta que doña Rosalinda, tomo las riendas de este negocio familiar. Doña Rosalinda, cuenta que en el Mercado No. 1 por casi 21 años comercializó su producto, hasta que en tiempos del Alcalde “Oscar Emiro Barrios” se trasladó a la Nueva Terminal, ubicada en Cantón el Mosquito de este Municipio, luego del fallecimiento de su querido esposo. En este lugar tiene 22 años de vender y está ubicada en el cubículo No. 28 de la Central de autobuses que se dirigen a la Capital y otros lugares. Una anécdota que marco el negocio, fue cuando en la escuela a un hijo de Doña Rosalinda, le piden elaborar una historia y el plasmo en una hoja de su cuaderno de deberes las vivencias, en el negocio familia –el cual hasta el momento no tenía nombre-, y lo llamó Panificadora Rosita. El cual le hizo acreedor al primer lugar del concurso, siendo así como toma nombre el negocio, que representa para sus propietarios el legado de varias generaciones y el sueño hecho realidad de sus antepasados.','','59810337','Rosalinda Rivera González','',now(),now()); 



insert into usuario values(6,'Panadería Industrial','','direccion','descripcion','logo','telefono','propietario','fotografia',now(),now());